services:
  foxel:
    image: ghcr.io/drizzletime/foxel:last
    container_name: foxel
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      - TZ=Asia/Shanghai
      - SECRET_KEY=EnsRhL9NFPxgFVc+7t96/y70DIOR+9SpntcIqQa90TU=
      - TEMP_LINK_SECRET_KEY=EnsRhL9NFPxgFVc+7t96/y70DIOR+9SpntcIqQa90TU=
    volumes:
      - ./data:/app/data
    pull_policy: always
    networks:
      - foxel-network

networks:
  foxel-network:
    driver: bridge